// app/layout.js

import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/app/lib/AuthContext"; // Import kontekstu

// Definicja fontów
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Aplikacja jest dostępna tylko dla zalogowanych użytkowników */}
        <AuthProvider>
          <SideBar>{children}</SideBar> {/* Zawartość aplikacji */}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
